name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: pocast
          POSTGRES_PASSWORD: pocast
          POSTGRES_DB: pocast_catalog_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U pocast -d pocast_catalog_test"
          --health-interval 5s --health-timeout 5s --health-retries 10

    env:
      CATALOG_TEST_DATABASE_URL: postgresql://pocast:pocast@localhost:5432/pocast_catalog_test
      AUTH_TEST_DATABASE_URL: postgresql://pocast:pocast@localhost:5432/pocast_auth_test

    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm check:deps
      - run: pnpm nx sync:check
      - run: pnpm nx format:check
      - run: PGPASSWORD=pocast psql -h localhost -U pocast -d pocast_catalog_test -c 'CREATE DATABASE pocast_auth_test'
      - run: pnpm nx run-many -t prisma-deploy-test
      - run: pnpm nx affected -t lint test build typecheck
